development:
  adapter: redis
  url: <%= ENV.fetch("XIM_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: xrd_dev

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("XIM_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: xrd_prod
