default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['XIM_DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xim_dev

test:
  <<: *default
  database: xim_test